### ISSUE TITLE
Plugin ImproveOSM must be updated to JOSM 12682+

### ISSUE THREAD

**Issue by don-vip** [Telenav/improve-osm-plugin#16]
Hello,
The plugin must be updated to latest JOSM core changes, see https://josm.openstreetmap.de/ticket/15213
A lot of users are creating bug reports.
Thanks,
Vincent

**Comment by mvexel** [comment]
Hi @don-vip -- @beataj-telenav will be back soon and we will make sure this is handled with priority.

Out of curiosity -- how much time does the JOSM team give plugin developers to prepare for changes in the JOSM core that could break plugins?

**Comment by stoecker** [comment]
JOSM has a monthly release cycle. Most reports will come as soon as the next latest is released. First reports will usually comes a few days after the change. Updates could be continuous, as JOSM plugins allow to specify old versions, so that a new plugin does not break old releases, which means you can release an updated plugin as soon as the change in core was done. A nightly check (or the JOSM nightly checks) could inform you of changes requiring a re-release (relatively seldom).

**Comment by don-vip** [comment]
We are currently attempting to modularize JOSM. We try to avoid plugin breakages, but some are inevitable, and some are completely missed, like this one. I didn't expect a plugin to use the `GuiSizesHelper` class and I went the careless way by moving the class instead of deprecating it. For most of the changes we're doing it the safe way by deprecating a lot of public APIs. I expect to remove these deprecated APIs at the end of the year. This gives 4 months to plugin maintainers and us to update plugins code.

**Comment by stoecker** [comment]
This is currently our most-reported bug!

**Comment by don-vip** [comment]
I tried to create a PR but I don't event understand why the bug occurs, as ImproveOSM does use directly this class. It may be caused by the "josm-common" library, is it open source? I can't find it on Github.

**Comment by beataj-telenav** [comment]
Hello, sorry for the late response, but I was on holiday for 2 weeks. We will update our plugins to the latest JOSM core version.

**Comment by beataj-telenav** [comment]
The issue was fixed in build 119.
